language: node_js
sudo: required
dist: trusty
node_js:
  - '6'
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g bower
  - bower install
before_deploy:
  - npm run build
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: gdgspainsummit
    token: $FIREBASE_TOKEN
    on:
      branch: master